"""
Django settings for DjangoGirlsProject project.

Generated by 'django-admin startproject' using Django 3.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
# import pymysql as db # pridane kvoli MySql, ale asi nemusi to tu byt
import os
import _locale  # pridane nove kvoli dump-u
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])  # pridane nove kvoli dump-u

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tmfup!d-x14%-g6krp6j*txzuziub)qjfo%!^v%-db6fi81zk-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False                         # pri True je debagovanie t.j. hladanie chyb

# ALLOWED_HOSTS = []     # povodne - vtedy je host overovany vôči ['localhost', '127.0.0.1', '[::1]']
ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']    # pridane kvoli hostname na PythonAnywhere

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',    # pridane - Djangu sme povedali že má použiť novu appl. blog
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoGirlsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
#        'DIRS': [BASE_DIR + '/templates'],  # hadzalo to tu chybu --> + '/
        'APP_DIRS': True,                   # BASE_DIR tu je DjangoGirlsProject
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoGirlsProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        #   'ENGINE': 'django.db.backends.sqlite3',         nahradilo to povodne
        #   'NAME': BASE_DIR / 'db.sqlite3',             toto je povodne
        #   'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),   nahradilo sa povodne
        #   treba ale v terminaly vytvorit databazu prikazom python manage.py migrate

        # Django MySQL database engine driver class.
        'ENGINE': 'django.db.backends.mysql',
        # MySQL database host ip.
        'HOST': '127.0.0.1',
        # port number.
        'PORT': '3306',
        # database name.
        'NAME': 'djangogirlsproject',
        # user name.
        'USER': 'root',
        # password
        'PASSWORD': '10042018-Tomo',
        # connect options
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", },

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'         # povodne 'en-us' nove sk-sk

TIME_ZONE = 'UTC'     # povodne 'UTC' nove Europe/Bratislava

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')    # pridana cesta pre statické súbory

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # pridane
